[package]
name = "webui_server"
description = ""
authors=["smokingplaya"]
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
actix-web = "4.9.0"
anyhow = "1.0.94"
gmod = "17.0.0"
mime_guess = "2.0.5"
tokio = "1.42.0"
