name: WebUI-Server Build

on:
  push:
    branches:
      - master

jobs:
  build-linux32:
    name: Build Linux 32-bit
    runs-on: ubuntu-latest
    env:
      TARGET: i686-unknown-linux-gnu
    steps:
    - uses: actions/checkout@v2
    - run: |
        rustup install nightly
        rustup default nightly
    - uses: actions-rs/toolchain@v1
      with:
        profile: default
        toolchain: nightly
    - run: cargo build --release
    - uses: actions/upload-artifact@v4
      with:
        name: gmsv_webui_server_linux.dll
        path: target/release/libwebui_server.so

  build-linux64:
    name: Build Linux 64-bit
    runs-on: ubuntu-latest
    env:
      TARGET: x86_64-unknown-linux-gnu
    steps:
    - uses: actions/checkout@v2
    - run: |
        rustup install nightly
        rustup default nightly
    - uses: actions-rs/toolchain@v1
      with:
        profile: default
        toolchain: nightly
    - run: cargo build --release
    - uses: actions/upload-artifact@v4
      with:
        name: gmsv_webui_server_linux64.dll
        path: target/release/libwebui_server.so

  build-win64:
    name: Build Windows 64-bit
    runs-on: windows-latest
    env:
      TARGET: x86_64-pc-windows-msvc
    steps:
    - uses: actions/checkout@v2
    - run: |
        rustup install nightly
        rustup default nightly
    - uses: actions-rs/toolchain@v1
      with:
        profile: default
        toolchain: nightly
    - run: cargo build --release
    - uses: actions/upload-artifact@v4
      with:
        name: gmsv_webui_server_win64.dll
        path: target/release/webui_server.dll

  build-win32:
    name: Build Windows 32-bit
    runs-on: windows-latest
    env:
      TARGET: i686-pc-windows-msvc
    steps:
    - uses: actions/checkout@v2
    - run: |
        rustup install nightly
        rustup default nightly
    - uses: actions-rs/toolchain@v1
      with:
        profile: default
        toolchain: nightly
    - run: cargo build --release
    - uses: actions/upload-artifact@v4
      with:
        name: gmsv_webui_server_win32.dll
        path: target/release/webui_server.dll
